"""initial schema

Revision ID: e0e5fb242077
Revises: 
Create Date: 2026-09-03 14:55:18.818945
"""
from alembic import op
import sqlalchemy as sa


revision = 'e0e5fb242077'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=64), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('reporter_id', sa.String(length=32), nullable=False),
    sa.Column('reported_user_id', sa.String(length=32), nullable=True),
    sa.Column('game_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('open', 'reviewing', 'resolved', 'dismissed', name='report_status'), nullable=False),
    sa.Column('resolved_by', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_game_id'), 'reports', ['game_id'], unique=False)
    op.create_index(op.f('ix_reports_reported_user_id'), 'reports', ['reported_user_id'], unique=False)
    op.create_index(op.f('ix_reports_reporter_id'), 'reports', ['reporter_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('bot_difficulty', sa.String(length=16), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('rooms',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('creator_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('created', 'waiting', 'ready', 'starting', 'ingame', 'closed', name='room_status'), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('rules_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rooms_invite_code'), 'rooms', ['invite_code'], unique=True)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('max_streak', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('peak_rating', sa.Integer(), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('room_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('waiting', 'playing', 'finished', 'aborted', name='game_status'), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=True),
    sa.Column('winner_team', sa.String(length=8), nullable=True),
    sa.Column('final_scores', sa.Text(), nullable=False),
    sa.Column('config', sa.Text(), nullable=False),
    sa.Column('rules_version', sa.String(length=32), nullable=False),
    sa.Column('seed', sa.BigInteger(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('aborted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room_players',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('room_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'seat', name='uq_room_seat')
    )
    op.create_index(op.f('ix_room_players_room_id'), 'room_players', ['room_id'], unique=False)
    op.create_index(op.f('ix_room_players_user_id'), 'room_players', ['user_id'], unique=False)
    op.create_table('game_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_game_id'), 'game_events', ['game_id'], unique=False)
    op.create_table('game_players',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=8), nullable=False),
    sa.Column('is_bot', sa.Boolean(), nullable=False),
    sa.Column('bot_difficulty', sa.String(length=16), nullable=True),
    sa.Column('connection_state', sa.Enum('connected', 'disconnected', 'reconnecting', 'bot_controlled', 'finished', name='conn_state'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'seat', name='uq_game_seat')
    )
    op.create_index(op.f('ix_game_players_game_id'), 'game_players', ['game_id'], unique=False)
    op.create_table('moves',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('game_id', sa.String(length=32), nullable=False),
    sa.Column('move_number', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=32), nullable=True),
    sa.Column('seat', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('card', sa.String(length=8), nullable=True),
    sa.Column('trump', sa.String(length=16), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('server_time', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'request_id', name='uq_game_request')
    )
    op.create_index(op.f('ix_moves_game_id'), 'moves', ['game_id'], unique=False)
    op.create_index('ix_moves_game_order', 'moves', ['game_id', 'move_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_moves_game_order', table_name='moves')
    op.drop_index(op.f('ix_moves_game_id'), table_name='moves')
    op.drop_table('moves')
    op.drop_index(op.f('ix_game_players_game_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_index(op.f('ix_game_events_game_id'), table_name='game_events')
    op.drop_table('game_events')
    op.drop_index(op.f('ix_room_players_user_id'), table_name='room_players')
    op.drop_index(op.f('ix_room_players_room_id'), table_name='room_players')
    op.drop_table('room_players')
    op.drop_table('games')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_rooms_invite_code'), table_name='rooms')
    op.drop_table('rooms')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_reports_reporter_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_reported_user_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_game_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
